# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui',
# licensing of 'home.ui' applies.
#
# Created: Tue Dec  3 20:06:58 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(460, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(Home)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Home)
        self.stackedWidget.setObjectName("stackedWidget")
        self.app_page = QtWidgets.QWidget()
        self.app_page.setObjectName("app_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.app_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.head_widget = QtWidgets.QWidget(self.app_page)
        self.head_widget.setObjectName("head_widget")
        self.head = QtWidgets.QHBoxLayout(self.head_widget)
        self.head.setContentsMargins(0, 0, 0, 0)
        self.head.setObjectName("head")
        self.label = QtWidgets.QLabel(self.head_widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setWeight(9)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 italic 40pt \"Arial\";\n"
"color: rgb(254, 226, 2);")
        self.label.setObjectName("label")
        self.head.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.head_widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.py_version = QtWidgets.QLabel(self.head_widget)
        self.py_version.setObjectName("py_version")
        self.verticalLayout_3.addWidget(self.py_version)
        self.line_2 = QtWidgets.QFrame(self.head_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.head.addLayout(self.verticalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.setting_btn = QtWidgets.QPushButton(self.head_widget)
        self.setting_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.setting_btn.setFlat(True)
        self.setting_btn.setObjectName("setting_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setting_btn)
        self.head.addLayout(self.formLayout)
        self.head.setStretch(0, 9)
        self.verticalLayout_2.addWidget(self.head_widget)
        self.scrollArea = QtWidgets.QScrollArea(self.app_page)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 438, 533))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.installed_layout = QtWidgets.QVBoxLayout()
        self.installed_layout.setSpacing(20)
        self.installed_layout.setObjectName("installed_layout")
        self.verticalLayout_6.addLayout(self.installed_layout)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.apps_layout = QtWidgets.QVBoxLayout()
        self.apps_layout.setSpacing(20)
        self.apps_layout.setObjectName("apps_layout")
        self.verticalLayout_6.addLayout(self.apps_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_2.setStretch(1, 8)
        self.stackedWidget.addWidget(self.app_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.setting_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.setting_page)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 416, 658))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(416, 16777215))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_2.addWidget(self.back_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 394, 509))
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.py_manage_btn = QtWidgets.QToolButton(self.page)
        self.py_manage_btn.setObjectName("py_manage_btn")
        self.verticalLayout_7.addWidget(self.py_manage_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 394, 509))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pypi_source = QtWidgets.QLineEdit(self.page_2)
        self.pypi_source.setObjectName("pypi_source")
        self.verticalLayout_9.addWidget(self.pypi_source)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.change_pypi_btn = QtWidgets.QPushButton(self.page_2)
        self.change_pypi_btn.setObjectName("change_pypi_btn")
        self.horizontalLayout.addWidget(self.change_pypi_btn)
        self.pypi_checkBox = QtWidgets.QCheckBox(self.page_2)
        self.pypi_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pypi_checkBox.setChecked(True)
        self.pypi_checkBox.setObjectName("pypi_checkBox")
        self.horizontalLayout.addWidget(self.pypi_checkBox)
        self.horizontalLayout.setStretch(1, 9)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 394, 509))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.install_path = QtWidgets.QLineEdit(self.page_3)
        self.install_path.setReadOnly(True)
        self.install_path.setObjectName("install_path")
        self.verticalLayout_8.addWidget(self.install_path)
        self.install_btn = QtWidgets.QPushButton(self.page_3)
        self.install_btn.setObjectName("install_btn")
        self.verticalLayout_8.addWidget(self.install_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.setting_page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Home)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        Home.setWindowTitle(QtWidgets.QApplication.translate("Home", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Home", "bee box", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Home", "Python版本:", None, -1))
        self.py_version.setText(QtWidgets.QApplication.translate("Home", "未选择", None, -1))
        self.setting_btn.setText(QtWidgets.QApplication.translate("Home", "⚙", None, -1))
        self.back_btn.setText(QtWidgets.QApplication.translate("Home", "<<返回", None, -1))
        self.py_manage_btn.setText(QtWidgets.QApplication.translate("Home", "⚙", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtWidgets.QApplication.translate("Home", "Python路径", None, -1))
        self.pypi_source.setText(QtWidgets.QApplication.translate("Home", "https://pypi.douban.com/simple", None, -1))
        self.change_pypi_btn.setText(QtWidgets.QApplication.translate("Home", "修改", None, -1))
        self.pypi_checkBox.setText(QtWidgets.QApplication.translate("Home", "启用", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtWidgets.QApplication.translate("Home", "PyPi源", None, -1))
        self.install_btn.setText(QtWidgets.QApplication.translate("Home", "选择安装路径", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtWidgets.QApplication.translate("Home", "安装路径", None, -1))

