# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui',
# licensing of 'home.ui' applies.
#
# Created: Wed Dec 25 14:20:01 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(476, 717)
        self.verticalLayout = QtWidgets.QVBoxLayout(Home)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(Home)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("image: url(:/icon/icon/CTPBEE.png);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(Home)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setting_btn = QtWidgets.QToolButton(Home)
        self.setting_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon)
        self.setting_btn.setIconSize(QtCore.QSize(25, 25))
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout_3.addWidget(self.setting_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.progressBar = QtWidgets.QProgressBar(Home)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.progressBar.setFont(font)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.scrollArea = QtWidgets.QScrollArea(Home)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 454, 541))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.installed_layout = QtWidgets.QVBoxLayout()
        self.installed_layout.setSpacing(10)
        self.installed_layout.setContentsMargins(-1, -1, 0, 5)
        self.installed_layout.setObjectName("installed_layout")
        self.verticalLayout_4.addLayout(self.installed_layout)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.apps_layout = QtWidgets.QVBoxLayout()
        self.apps_layout.setSpacing(10)
        self.apps_layout.setContentsMargins(-1, -1, -1, 5)
        self.apps_layout.setObjectName("apps_layout")
        self.verticalLayout_4.addLayout(self.apps_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.github = QtWidgets.QToolButton(Home)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github.setIcon(icon1)
        self.github.setObjectName("github")
        self.horizontalLayout_2.addWidget(self.github)
        self.qq = QtWidgets.QToolButton(Home)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/qq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qq.setIcon(icon2)
        self.qq.setObjectName("qq")
        self.horizontalLayout_2.addWidget(self.qq)
        self.toolButton = QtWidgets.QToolButton(Home)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 8)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        Home.setWindowTitle(QtWidgets.QApplication.translate("Home", "Home", None, -1))
        self.label.setToolTip(QtWidgets.QApplication.translate("Home", "组织标志", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Home", "bee box", None, -1))
        self.setting_btn.setToolTip(QtWidgets.QApplication.translate("Home", "设置", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Home", "可用", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Home", "所有", None, -1))
        self.github.setToolTip(QtWidgets.QApplication.translate("Home", "github", None, -1))
        self.qq.setToolTip(QtWidgets.QApplication.translate("Home", "<html><head/><body><p>ctpbee开源量化社区群：756319143</p></body></html>", None, -1))
        self.toolButton.setToolTip(QtWidgets.QApplication.translate("Home", "<html><head/><body><p>当前版本：1.0</p></body></html>", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("Home", "1.0", None, -1))

import app.resource.bee_box_rc
