# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_env.ui',
# licensing of 'new_env.ui' applies.
#
# Created: Wed Dec 25 11:07:50 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_NewEnv(object):
    def setupUi(self, NewEnv):
        NewEnv.setObjectName("NewEnv")
        NewEnv.resize(498, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/CTPBEE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewEnv.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewEnv)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(NewEnv)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(NewEnv)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.env_radio = QtWidgets.QRadioButton(NewEnv)
        self.env_radio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.env_radio.setChecked(True)
        self.env_radio.setObjectName("env_radio")
        self.verticalLayout_2.addWidget(self.env_radio)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(NewEnv)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.path = QtWidgets.QLineEdit(NewEnv)
        self.path.setObjectName("path")
        self.horizontalLayout_3.addWidget(self.path)
        self.path_btn = QtWidgets.QToolButton(NewEnv)
        self.path_btn.setObjectName("path_btn")
        self.horizontalLayout_3.addWidget(self.path_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(NewEnv)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.base_py_list = QtWidgets.QComboBox(NewEnv)
        self.base_py_list.setObjectName("base_py_list")
        self.horizontalLayout_2.addWidget(self.base_py_list)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.exit_radio = QtWidgets.QRadioButton(NewEnv)
        self.exit_radio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exit_radio.setObjectName("exit_radio")
        self.verticalLayout_2.addWidget(self.exit_radio)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(NewEnv)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.exis_path = QtWidgets.QLineEdit(NewEnv)
        self.exis_path.setObjectName("exis_path")
        self.horizontalLayout_4.addWidget(self.exis_path)
        self.exit_path_btn = QtWidgets.QToolButton(NewEnv)
        self.exit_path_btn.setObjectName("exit_path_btn")
        self.horizontalLayout_4.addWidget(self.exit_path_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.ok_btn = QtWidgets.QPushButton(NewEnv)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_5.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(NewEnv)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_5.addWidget(self.cancel_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(NewEnv)
        QtCore.QMetaObject.connectSlotsByName(NewEnv)

    def retranslateUi(self, NewEnv):
        NewEnv.setWindowTitle(QtWidgets.QApplication.translate("NewEnv", "新建虚拟环境", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("NewEnv", "名称", None, -1))
        self.env_radio.setText(QtWidgets.QApplication.translate("NewEnv", "新的虚拟环境", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("NewEnv", "位置", None, -1))
        self.path_btn.setText(QtWidgets.QApplication.translate("NewEnv", "...", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("NewEnv", "基于", None, -1))
        self.exit_radio.setText(QtWidgets.QApplication.translate("NewEnv", "选取外部环境", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("NewEnv", "位置", None, -1))
        self.exit_path_btn.setText(QtWidgets.QApplication.translate("NewEnv", "...", None, -1))
        self.ok_btn.setText(QtWidgets.QApplication.translate("NewEnv", "确定", None, -1))
        self.cancel_btn.setText(QtWidgets.QApplication.translate("NewEnv", "取消", None, -1))

import app.resource.bee_box_rc
