# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui',
# licensing of 'setting.ui' applies.
#
# Created: Tue Nov 19 15:29:32 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(401, 560)
        self.verticalLayout = QtWidgets.QVBoxLayout(Setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Setting)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.py_path_tip = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.py_path_tip.setText("")
        self.py_path_tip.setObjectName("py_path_tip")
        self.horizontalLayout_8.addWidget(self.py_path_tip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.py_path_box = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.py_path_box.setObjectName("py_path_box")
        self.py_path_box.addItem("")
        self.horizontalLayout_9.addWidget(self.py_path_box)
        self.py_path_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.py_path_btn.setObjectName("py_path_btn")
        self.horizontalLayout_9.addWidget(self.py_path_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.pypi_tip = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.pypi_tip.setText("")
        self.pypi_tip.setObjectName("pypi_tip")
        self.horizontalLayout_10.addWidget(self.pypi_tip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.pypi_source = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.pypi_source.setObjectName("pypi_source")
        self.verticalLayout_2.addWidget(self.pypi_source)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.change_pypi_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.change_pypi_btn.setObjectName("change_pypi_btn")
        self.horizontalLayout_11.addWidget(self.change_pypi_btn)
        self.pypi_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.pypi_checkBox.setChecked(True)
        self.pypi_checkBox.setObjectName("pypi_checkBox")
        self.horizontalLayout_11.addWidget(self.pypi_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.install_tip = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.install_tip.setText("")
        self.install_tip.setObjectName("install_tip")
        self.horizontalLayout_12.addWidget(self.install_tip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.install_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.install_path.setReadOnly(True)
        self.install_path.setObjectName("install_path")
        self.horizontalLayout_13.addWidget(self.install_path)
        self.install_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.install_btn.setObjectName("install_btn")
        self.horizontalLayout_13.addWidget(self.install_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        Setting.setWindowTitle(QtWidgets.QApplication.translate("Setting", "配置", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Setting", "python路径", None, -1))
        self.py_path_box.setItemText(0, QtWidgets.QApplication.translate("Setting", "未选择", None, -1))
        self.py_path_btn.setText(QtWidgets.QApplication.translate("Setting", "...", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Setting", "pypi源", None, -1))
        self.pypi_source.setText(QtWidgets.QApplication.translate("Setting", "https://pypi.douban.com/simple", None, -1))
        self.change_pypi_btn.setText(QtWidgets.QApplication.translate("Setting", "修改", None, -1))
        self.pypi_checkBox.setText(QtWidgets.QApplication.translate("Setting", "启用", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Setting", "安装路径", None, -1))
        self.install_btn.setText(QtWidgets.QApplication.translate("Setting", "选择安装路径", None, -1))

